# Generated by Django 2.0.2 on 2018-05-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180517_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='course',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meta',
            name='session',
            field=models.IntegerField(default=2),
        ),
    ]
